/*
 * Copyright (C) 2017 andres.velez
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.avpsoft.jhashcalc.gui;

import com.avpsoft.jhashcalc.crypto.Hash;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author andres.velez
 */
public class Interface extends javax.swing.JFrame {

    private final JFileChooser jFileChooser = new JFileChooser();
    private final TextDialog jTextDialog;
    private File fileHash;
    private String textHash;

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();

        jTextDialog = new TextDialog(this, true);
        jFileChooser.setMultiSelectionEnabled(false);
        
        jTextFieldCompare.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                compare();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                compare();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                compare();
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRadioOptions = new javax.swing.ButtonGroup();
        jPanelOptions = new javax.swing.JPanel();
        jRadioButtonText = new javax.swing.JRadioButton();
        jRadioButtonFile = new javax.swing.JRadioButton();
        jButtonOpen = new javax.swing.JButton();
        jTextFieldData = new javax.swing.JTextField();
        jPanelHashCalc = new javax.swing.JPanel();
        jComboBoxHash = new javax.swing.JComboBox();
        jSeparatorHash = new javax.swing.JSeparator();
        jButtonCalculate = new javax.swing.JButton();
        jTextFieldResult = new javax.swing.JTextField();
        jLabelCompare = new javax.swing.JLabel();
        jTextFieldCompare = new javax.swing.JTextField();
        jLabelCompareResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("jHashCalc");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanelOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        buttonGroupRadioOptions.add(jRadioButtonText);
        jRadioButtonText.setText("Write Text");

        buttonGroupRadioOptions.add(jRadioButtonFile);
        jRadioButtonFile.setSelected(true);
        jRadioButtonFile.setText("Open File");

        jButtonOpen.setText("Open");
        jButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenActionPerformed(evt);
            }
        });

        jTextFieldData.setEditable(false);

        javax.swing.GroupLayout jPanelOptionsLayout = new javax.swing.GroupLayout(jPanelOptions);
        jPanelOptions.setLayout(jPanelOptionsLayout);
        jPanelOptionsLayout.setHorizontalGroup(
            jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldData)
                    .addGroup(jPanelOptionsLayout.createSequentialGroup()
                        .addComponent(jRadioButtonFile, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonText, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelOptionsLayout.setVerticalGroup(
            jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonFile)
                    .addComponent(jRadioButtonText)
                    .addComponent(jButtonOpen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelHashCalc.setBorder(javax.swing.BorderFactory.createTitledBorder("Hash Calculator"));

        jComboBoxHash.setModel(new javax.swing.DefaultComboBoxModel(Hash.GNU_HASHES.toArray(new String[0])));

        jButtonCalculate.setText("Calculate");
        jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateActionPerformed(evt);
            }
        });

        jTextFieldResult.setEditable(false);

        jLabelCompare.setText("Compare (Paste your hash here) :");

        jLabelCompareResult.setPreferredSize(new java.awt.Dimension(164, 14));

        javax.swing.GroupLayout jPanelHashCalcLayout = new javax.swing.GroupLayout(jPanelHashCalc);
        jPanelHashCalc.setLayout(jPanelHashCalcLayout);
        jPanelHashCalcLayout.setHorizontalGroup(
            jPanelHashCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHashCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHashCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparatorHash)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelHashCalcLayout.createSequentialGroup()
                        .addComponent(jComboBoxHash, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextFieldCompare, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldResult, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHashCalcLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelCompare)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCompareResult, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelHashCalcLayout.setVerticalGroup(
            jPanelHashCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHashCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHashCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCalculate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparatorHash, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHashCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCompare)
                    .addComponent(jLabelCompareResult, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jTextFieldCompare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelHashCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelHashCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenActionPerformed

        int showOpenDialog;
        textHash = null;
        fileHash = null;
        jTextFieldResult.setText("");
        jTextFieldData.setText("");

        if (jRadioButtonText.isSelected()) {
            showOpenDialog = jTextDialog.showOpenDialog();
            if (TextDialog.RET_OK == showOpenDialog) {
                textHash = jTextDialog.getText();
                jTextFieldData.setText( textHash.length() > 50 ? textHash.substring(0,47)+"..." : textHash );
            }
        } else if (jRadioButtonFile.isSelected()) {
            showOpenDialog = jFileChooser.showOpenDialog(Interface.this);
            if (JFileChooser.APPROVE_OPTION == showOpenDialog) {
                fileHash = jFileChooser.getSelectedFile();
                try{
                    String path = fileHash.getCanonicalPath();
                    jTextFieldData.setText( path.length() > 50 ? "..." +path.substring(path.length()-47,path.length()): path );
                }catch(Exception ignore){
                    ignore.printStackTrace(System.out);
                }
            }
        }
    }//GEN-LAST:event_jButtonOpenActionPerformed

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed

        String algoritmo = (String) jComboBoxHash.getModel().getSelectedItem();
        String hash = "";

        if (jRadioButtonFile.isSelected() && fileHash != null) {
            try {
                hash = Hash.getHash(fileHash, algoritmo).get(algoritmo);
            } catch (IOException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (jRadioButtonText.isSelected() && textHash != null) {
            hash = Hash.getHash(textHash, algoritmo);
        }
        if(!"".equals(hash) && algoritmo.compareToIgnoreCase("Base64") == 0) {
            hash = Hash.hexToASCII(hash);
        }
        jTextFieldResult.setText(hash);
        compare();
    }//GEN-LAST:event_jButtonCalculateActionPerformed

    private void compare() {
        
        jLabelCompareResult.setText("NONE");
        String hashResult = jTextFieldResult.getText();
        String hashCompare = jTextFieldCompare.getText();
        
        if(hashResult != null && hashCompare != null) {
            if(hashResult.compareTo(hashCompare) == 0) {
                jLabelCompareResult.setText("OK");
            }
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRadioOptions;
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JButton jButtonOpen;
    private javax.swing.JComboBox jComboBoxHash;
    private javax.swing.JLabel jLabelCompare;
    private javax.swing.JLabel jLabelCompareResult;
    private javax.swing.JPanel jPanelHashCalc;
    private javax.swing.JPanel jPanelOptions;
    private javax.swing.JRadioButton jRadioButtonFile;
    private javax.swing.JRadioButton jRadioButtonText;
    private javax.swing.JSeparator jSeparatorHash;
    private javax.swing.JTextField jTextFieldCompare;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldResult;
    // End of variables declaration//GEN-END:variables
}
